In [1]:
import numpy as np

In [20]:
#Question 1:
x=np.array([1,2,35,8,9])
x.tolist()

[1, 2, 35, 8, 9]

In [28]:
#Question 2:
b=np.array([[1,2,3],[5,8,9],[12,8,3]])
h=np.trace(b)
print(h)

12


In [70]:
#Question 3:
array=np.array([[1,2,3],[5,9,3]])
x=int(input("give x:"))
print(array[array>x])

give x:3
[5 9]


In [79]:
#Question 4:
A=np.array([[1,2,3],[5,4,1],[3,9,2]])
B=np.array([[8,5,6],[1,9,8],[2,1,4]])
C = np.add(A,B)
print(C)

[[ 9  7  9]
 [ 6 13  9]
 [ 5 10  6]]


In [87]:
#Question 5:
D=np.array([[1,2,3],[6,9,2],[3,2,7]])
E=D-D.mean(axis=1,keepdims=True)
print(E)

[[-1.          0.          1.        ]
 [ 0.33333333  3.33333333 -3.66666667]
 [-1.         -2.          3.        ]]
